// =============================================
// DAVILA'S MARKETING — Admin Panel JS
// Stores businesses in localStorage and keeps
// the registry in sync for the main site.
// =============================================

const STORAGE_KEY = 'davilas_businesses';

// ── LOAD / SAVE ──
function getBusinesses() {
  return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
}

function saveBusinesses(list) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(list));
  syncRegistry(list);
}

// ── SYNC: generates the registry JS content and shows it ──
function syncRegistry(list) {
  const entries = list.map(b => `  {
    slug:        '${slugify(b.name)}',
    name:        '${esc(b.name)}',
    category:    '${esc(b.category)}',
    description: '${esc(b.description)}',
    image:       '${esc(b.heroImage || '')}',
    path:        '../negocios/${slugify(b.name)}/index.html',
    date:        '${esc(b.date || new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }))}',
  }`).join(',\n');

  const content = `// AUTO-GENERATED by Admin Panel — do not edit manually\nconst BUSINESSES_REGISTRY = [\n${entries}\n];\n`;

  // Store generated registry so it can be copied
  localStorage.setItem('davilas_registry', content);
}

// ── RENDER LIST ──
function renderList() {
  const list = getBusinesses();
  const container = document.getElementById('businessesList');

  if (!list.length) {
    container.innerHTML = `<div class="empty-state"><span>🏢</span>No businesses yet. Click "+ Add Business" to get started.</div>`;
    return;
  }

  container.innerHTML = list.map((b, i) => `
    <div class="biz-admin-card">
      ${b.heroImage
        ? `<img class="biz-admin-card-img" src="${b.heroImage}" alt="${b.name}" onerror="this.style.display='none'" />`
        : `<div class="biz-admin-card-img-placeholder">🏢</div>`}
      <div class="biz-admin-card-body">
        <span class="tag">${b.category}</span>
        <h3>${b.name}</h3>
        <p>${b.description}</p>
        <div class="biz-admin-card-actions">
          <button class="btn-edit" onclick="openEdit(${i})">✏️ Edit</button>
          <a class="btn-view" href="../negocios/${slugify(b.name)}/index.html" target="_blank">🔗</a>
          <button class="btn-delete" onclick="deleteBusiness(${i})">🗑️</button>
        </div>
      </div>
    </div>`).join('');
}

// ── OPEN MODAL ──
function openAdd() {
  document.getElementById('modalTitle').textContent = 'Add Business';
  document.getElementById('bizForm').reset();
  document.getElementById('bizIndex').value = -1;
  document.getElementById('modalOverlay').classList.add('open');
}

function openEdit(i) {
  const b = getBusinesses()[i];
  document.getElementById('modalTitle').textContent = 'Edit Business';
  document.getElementById('bizIndex').value = i;
  document.getElementById('bizName').value        = b.name        || '';
  document.getElementById('bizCategory').value    = b.category    || '';
  document.getElementById('bizDescription').value = b.description || '';
  document.getElementById('bizPhone').value       = b.phone       || '';
  document.getElementById('bizEmail').value       = b.email       || '';
  document.getElementById('bizAddress').value     = b.address     || '';
  document.getElementById('bizHours').value       = b.hours       || '';
  document.getElementById('bizWebsite').value     = b.website     || '';
  document.getElementById('bizHeroImage').value   = b.heroImage   || '';
  document.getElementById('bizServices').value    = (b.services || []).join('\n');
  document.getElementById('bizGallery').value     = (b.gallery   || []).join('\n');
  document.getElementById('modalOverlay').classList.add('open');
}

function closeModal() {
  document.getElementById('modalOverlay').classList.remove('open');
}

// ── SAVE FORM ──
document.getElementById('bizForm').addEventListener('submit', e => {
  e.preventDefault();
  const list  = getBusinesses();
  const index = parseInt(document.getElementById('bizIndex').value);

  const biz = {
    name:        document.getElementById('bizName').value.trim(),
    category:    document.getElementById('bizCategory').value.trim(),
    description: document.getElementById('bizDescription').value.trim(),
    phone:       document.getElementById('bizPhone').value.trim(),
    email:       document.getElementById('bizEmail').value.trim(),
    address:     document.getElementById('bizAddress').value.trim(),
    hours:       document.getElementById('bizHours').value.trim(),
    website:     document.getElementById('bizWebsite').value.trim(),
    heroImage:   document.getElementById('bizHeroImage').value.trim(),
    services:    document.getElementById('bizServices').value.split('\n').map(s => s.trim()).filter(Boolean),
    gallery:     document.getElementById('bizGallery').value.split('\n').map(s => s.trim()).filter(Boolean),
    date:        new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
  };

  if (index === -1) {
    list.push(biz);
  } else {
    list[index] = { ...list[index], ...biz };
  }

  saveBusinesses(list);
  generateBusinessPage(biz);
  closeModal();
  renderList();
  showToast(index === -1 ? 'Business added ✓' : 'Business updated ✓');
});

// ── DELETE ──
function deleteBusiness(i) {
  if (!confirm('Delete this business?')) return;
  const list = getBusinesses();
  list.splice(i, 1);
  saveBusinesses(list);
  renderList();
  showToast('Business deleted');
}

// ── AUTO-GENERATE business page HTML ──
function generateBusinessPage(b) {
  const slug = slugify(b.name);
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${b.name} — Davila's Marketing</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="../../negocios/business.css" />
</head>
<body>
  <nav class="biz-nav">
    <a href="../../Pagina principal/index.html" class="biz-nav-logo">
      <span class="logo-main">DAVILA'S</span>
      <span class="logo-sub">Marketing</span>
    </a>
    <a href="../../Pagina principal/index.html#businesses" class="biz-nav-back">← Back to Businesses</a>
  </nav>
  <section class="biz-hero" id="bizHero"></section>
  <div class="biz-layout">
    <div>
      <div class="biz-content-card" style="margin-bottom:24px;">
        <h2>About</h2>
        <p id="bizDescription"></p>
      </div>
      <div id="bizGallery"></div>
      <div id="bizReviews" style="margin-top:24px;"></div>
    </div>
    <div class="biz-sidebar">
      <div id="bizInfo"></div>
      <div id="bizServices"></div>
    </div>
  </div>
  <footer class="biz-footer">
    <p>Powered by <a href="../../Pagina principal/index.html">Davila's Marketing</a> &nbsp;|&nbsp; &copy;2025 All rights reserved.</p>
  </footer>
  <script src="../../negocios/business.js"></script>
  <script>
    window.BIZ_CONFIG = ${JSON.stringify(b, null, 4)};
    document.addEventListener('DOMContentLoaded', () => {
      const el = document.getElementById('bizDescription');
      if (el) el.textContent = window.BIZ_CONFIG.description;
    });
  </script>
</body>
</html>`;

  // Store generated HTML so user can copy/download it
  localStorage.setItem(`davilas_page_${slug}`, html);
  showGeneratedCode(slug, html, b);
}

// ── SHOW GENERATED CODE PANEL ──
function showGeneratedCode(slug, html, b) {
  // Remove existing panel if any
  document.getElementById('codePanel')?.remove();

  const panel = document.createElement('div');
  panel.id = 'codePanel';
  panel.style.cssText = `
    position:fixed; bottom:0; left:220px; right:0;
    background:#0d0f1a; color:#e8eaf0; padding:20px 28px;
    border-top:2px solid #1a6fd4; z-index:150; font-family:monospace; font-size:0.78rem;
  `;
  panel.innerHTML = `
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;">
      <span style="font-weight:700;color:#4a9fff;">📄 Page generated for: <strong>${b.name}</strong></span>
      <div style="display:flex;gap:10px;">
        <button onclick="copyCode('${slug}')" style="background:#1a6fd4;color:#fff;border:none;padding:6px 14px;border-radius:6px;cursor:pointer;font-weight:700;">Copy HTML</button>
        <button onclick="document.getElementById('codePanel').remove()" style="background:none;border:1px solid #444;color:#aaa;padding:6px 12px;border-radius:6px;cursor:pointer;">✕ Close</button>
      </div>
    </div>
    <p style="color:#8a9ab8;font-size:0.75rem;">
      📁 Save this file as: <code style="color:#4a9fff;">negocios/${slug}/index.html</code>
      &nbsp;|&nbsp; Then add to registry: <code style="color:#4a9fff;">negocios/businesses-registry.js</code>
    </p>`;
  document.body.appendChild(panel);
}

window.copyCode = function(slug) {
  const html = localStorage.getItem(`davilas_page_${slug}`);
  navigator.clipboard.writeText(html).then(() => showToast('HTML copied to clipboard ✓'));
};

// ── UTILS ──
function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}
function esc(str) {
  return String(str).replace(/'/g, "\\'");
}

function showToast(msg) {
  let t = document.querySelector('.toast');
  if (!t) { t = document.createElement('div'); t.className = 'toast'; document.body.appendChild(t); }
  t.textContent = msg;
  t.classList.add('show');
  setTimeout(() => t.classList.remove('show'), 3000);
}

// ── EVENTS ──
document.getElementById('btnAdd').addEventListener('click', openAdd);
document.getElementById('modalClose').addEventListener('click', closeModal);
document.getElementById('btnCancel').addEventListener('click', closeModal);
document.getElementById('modalOverlay').addEventListener('click', e => {
  if (e.target === document.getElementById('modalOverlay')) closeModal();
});

// ── INIT ──
renderList();
